### ISSUE TITLE
[npmgraph.js.org]  "MultipleAllowOriginValues" error in Chrome

### ISSUE THREAD

**Issue by broofa** [npmjs-cf/meta#7]
npmgraph.js.org is broken at the moment, due to requests to npmjs.cf failing with the following error:
<img width="802" alt="CleanShot 2022-04-13 at 08 05 52@2x" src="https://user-images.githubusercontent.com/164050/163211253-b65ac7ed-2686-4540-b7c4-a77f646a29ba.png">

E.g. https://npmgraph.js.org/?q=uuid

It looks like the server is responding with duplicate `access-control-allow-origin` header values:
![CleanShot 2022-04-13 at 08 07 30@2x](https://user-images.githubusercontent.com/164050/163211676-1a3301be-7bfa-448b-b2b1-aa87ab61e5a5.png)

If I had to guess, I'd say this has been this way for awhile but this is now considered an error in the latest release of Chrome.

**Comment by terinjokes** [comment]
I'll fix this today. But note that npm now sends CORS headers, so you should be able to talk directly to the registry.

**Comment by terinjokes** [comment]
Should be resolved now.

**Comment by broofa** [comment]
Hmm.  Still seeing this issue.  😖 

![CleanShot 2022-04-13 at 16 22 00@2x](https://user-images.githubusercontent.com/164050/163285413-e820ada1-7588-4a26-a47d-576561bd029d.png)

**Comment by terinjokes** [comment]
I reverted because this is a temporary test from npm to identify issues like this before a full roll out later this month. I'd be implementing a more complete fix for their upcoming changes this week.

Sorry for the temporary outage.
